---
name: Add folder for new program  request
on:
  issues:
    types: labeled
jobs:
  detectlabel:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issues.labels == 'NEW PROGRAM REQUEST' }}
    if: github.event.label.name == 'bug'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@v1.70.1
        with:
          ruby-version: 2.7
      - name: run ruby script
        id: ruby_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Program title: ${{ github.event.issue.title }}-${{ github.event.issue.number }}"
          echo "Issue ID: ${{ github.event.issue.number }}"
          cd "$GITHUB_WORKSPACE/.github/createProgramFolder"
          ruby programFolder.rb -e createGitBranch $GITHUB_WORKSPACE/guides-and-templates "${{ github.event.issue.title }}-${{ github.event.issue.number }}" $GITHUB_WORKSPACE/programs
          echo -n "::set-output name=FORMATTEDID::"
          echo ${{ github.event.issue.title }}-${{ github.event.issue.number}} | sed -e 's/[^0-9A-Za-z]/_/g'
          echo "Ruby Scripts, FORMATTEDID: ${{ steps.ruby_script.outputs.FORMATTEDID }}"
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Templates added by Oddb0t
          branch: ${{ steps.ruby_script.outputs.FORMATTEDID }}
          commit-message: Templates added to the new program by Oddb0t checkout
