---
name: Add folder for new program  request
on:
  issues:
    types: labeled
jobs:
  detectlabel:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issues.labels == 'NEW PROGRAM REQUEST' }}
    if: github.event.label.name == 'bug'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@v1.70.1
        with:
          ruby-version: 2.7
      - run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue ID: ${{ github.event.issue.id }}"
          cd "$GITHUB_WORKSPACE/.github/createProgramFolder"
          ruby programFolder.rb $GITHUB_WORKSPACE/guides-and-templates ${{ github.event.issue.title }}-${{ github.event.issue.id }} $GITHUB_WORKSPACE/programs
          gh --version
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Templates added by Oddb0t
          branch: testing-2 # ${{ github.event.issues.title }}-${{ github.event.issues.id }}
          commit-message: Templates added to the new program by Oddb0t checkout
