---
name: Get Label Name
on:
  issues:
    types: labeled
jobs:
  detectlabel:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issues.labels == 'NEW PROGRAM REQUEST' }}
    # if: github.event.label.name == 'bug'
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  checkout:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN }}
  createBranch:
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.70.1
      with:
        ruby-version: 2.7
    - run: ruby ../createProgramFolder/programFolder.rb $GITHUB_WORKSPACE/guides-and-templates format({0}-{1}, github.event.issues.title github.event.issues.id)
