---
name: Get Label Name
on:
  issues:
    types: labeled
jobs:
  detectlabel:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issues.labels == 'NEW PROGRAM REQUEST' }}
    if: github.event.label.name == 'bug'
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Folder created for issue in programs/'
              })
