---
name: Add folder for new program  request
on:
  issues:
    types: labeled
jobs:
  detectlabel:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issues.labels == 'NEW PROGRAM REQUEST' }}
    if: github.event.label.name == 'bug'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@v1.70.1
        with:
          ruby-version: 2.7
      - run: |
          cd "$GITHUB_WORKSPACE/.github/createProgramFolder"
          ruby programFolder.rb $GITHUB_WORKSPACE/guides-and-templates ${{ github.event.issues.title }}-${{ github.event.issues.id }} $GITHUB_WORKSPACE/programs
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Templates added by Oddb0t
          branch: ${{ github.event.issues.title }}-${{ github.event.issues.id }}
          commit-message: Templates added to the new program by Oddb0t checkout
          # with:
          #   github-token: ${{ secrets.GITHUB_TOKEN }}
          #   with:
          #     title: Templates added by Oddb0t
          #     branch: format({0}-{1}, github.event.issues.title github.event.issues.id)
          #     commit-message: Templates added to the new program by Oddb0t checkout:
          #   - name: Checkout
          #     with:
          #       token: ${{secrets.GITHUB_TOKEN }}
        #  createBranch:
        #    - name: Setup Ruby, JRuby and TruffleRuby
        #      with:
        #        ruby-version: 2.7
        #    - run: ruby ../createProgramFolder/programFolder.rb $GITHUB_WORKSPACE/guides-and-templates format({0}-{1}, github.event.issues.title github.event.issues.id)
        # createPullRequest:
        #   - name: Create pull request for the new program
        #     uses: peter-evans/create-pull-request@v3
        #     with:
        #       title: Templates added by Oddb0t
        #       branch: format({0}-{1}, github.event.issues.title github.event.issues.id)
        #       commit-message: Templates added to the new program by Oddb0t
