---
name: Get Label Name
on:
  issues:
    types: labeled
jobs:
  detectlabel:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issues.labels == 'NEW PROGRAM REQUEST' }}
    if: github.event.label.name == 'bug'
    steps:
      - uses: dessant/label-actions@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          process-only: 'issues'
          run: echo 'We found an issue'
          # script: |
          #   github.issues.createComment({
          #     issue_number: context.issue_number,
          #     owner: context.repo.owner,
          #     repo: context.repo.repo,
          #     body: '✅ Folder created for issue in programs/'
          #   })
